version: "3"
services:
  rust-app:
    container_name: rust-app
    build:
      context: .
      dockerfile: ./docker/rust-app/Dockerfile.dev
      target: develop-stage
    expose:
      - 8080
    tty: true
    volumes:
      - ./rust-app:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
      - RUST_BACKTRACE=1
    working_dir: /app
    command: /bin/sh -c "cargo watch -x run"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    tty: true
    volumes:
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rust-app
  bff:
    container_name: bff
    build:
      context: .
      dockerfile: ./docker/bff/Dockerfile.dev
    tty: true
    env_file:
      - ./docker/bff/api.env
    volumes:
      - ./bff:/app
    ports:
      - "9000:9000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000

volumes:
  target-cache:
  cargo-cache: