version: "3"
services:
  rust-app:
    container_name: rust-app
    build:
      context: .
      dockerfile: ./docker/rust-app/Dockerfile.dev
      target: develop-stage
    expose:
      - 8080
    tty: true
    volumes:
      - ./rust-app:/app
    working_dir: /app
    command: /bin/sh -c "cargo watch -x run"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    tty: true
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
