version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/cpu/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    tty: true
    ipc: host
    labels:
      - com.example.type="gpu"
    command: uvicorn main:app --reload --host 0.0.0.0
